// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jursonmo/geektask/week04/blog/internal/biz"
	"github.com/jursonmo/geektask/week04/blog/internal/dao"
	"github.com/jursonmo/geektask/week04/blog/internal/server"
	"github.com/jursonmo/geektask/week04/blog/internal/service"
)

// Injectors from wire.go:

func initApp(logger log.Logger) (*kratos.App, error) {
	data := dao.NewData()
	articleRepo := dao.NewArticleRepo(data, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo)
	articleService := service.NewArticleService(logger, articleUsecase)
	myHttpServer := server.NewHttpServer(articleService)
	signalServer := server.NewSignalServer(logger)
	app := newApp(logger, myHttpServer, signalServer)
	return app, nil
}
